[green_agent]
agentbeats_id = "serjtroshin/pragmatic-builder"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", AGENT_QA_MODE = "openai", AGENT_TRANSCRIPT_DIR = "logs/transcripts" }

[[participants]]
name = "Rita"
agentbeats_id = "OWNER/AGENT_ID"
env = {}

[config]
"list1_path" = "../data/List1_FINAL_stimuli_list.csv"
"list2_path" = "../data/List2_FINAL_stimuli_list.csv"
